name = is_01
description = A 3 column layout with a prominent is_01 region.
preview = preview.png
template = is_01-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
; stylesheets[all][] = css/layouts/is_01/is_01.layout.css
; stylesheets[all][] = css/layouts/is_01/is_01.layout.no-query.css
